### ISSUE TITLE
Some FLAC files showing as 0:00 track duration and will only play a few seconds.

### ISSUE THREAD

**Issue by donutmiddles** [airsonic-advanced/airsonic-advanced#562] opened 2021-07-02 05:27 UTC
## Problem description

Since upgrading from the latest stable Airsonic to the lastest EDGE version of Airsonic-Advanced, some of my FLAC files which all previously displayed and played fine, now show as 0:00 for the track duration and will only play for a few seconds before stopping. This happens whehter playing from the web player or an app like DSub or Ultrasonic.

The database did upgrade fine, as evidenced in the log file:
2021-07-01 21:47:11.548  INFO --- o.a.p.u.LegacyHsqlMigrationUtil          : HSQLDB database upgrade needed, from version 1.8.0 to 2.5
2021-07-01 21:47:11.793  INFO --- o.a.p.u.LegacyHsqlMigrationUtil          : HSQLDB database backed up to /mnt/dietpi_userdata/airsonic/db.backup.20210701214711
2021-07-01 21:47:37.796  INFO --- o.a.p.u.LegacyHsqlMigrationUtil          : HSQLDB database has been upgraded
2021-07-01 21:47:37.798  INFO --- o.a.p.u.LegacyHsqlMigrationUtil          : HSQLDB database version is now 2.5.0

The error I see in the logs when attempting to play one of these 0:00 duration files is (just with different timestamps depending when I try, obviously):
2021-07-01 23:47:41.305 WARN --- o.a.p.c.StreamController : Stream output exceeded expected length of 48000. It is likely that the transcoder is not adhering to the bitrate limit or the media source is corrupted or has grown larger

I have not changed the default transcoding strings, and my user is set to an Unlimited bitrate as has been the case for the whole time. Also, just in case, I ran some of the files through the FLAC integrity check in foobar as well as audioTester and both came back with no errors and matching CRCs. The file tags also have not been modified, but for some reason the new database seems to show them as seemingly empty somehow? Did also try cleaning the database and rebuilding it, but albums that were showing all 0:00 track lenghts continue to do so.

### Steps to reproduce

1. Browse to a FLAC folder in either the web client or standalone app.
2. Observe the track length shows 0:00 where it prior showed the proper length.
3. Attempt to play it, you will only hear a few seconds before it skips to the next track (or ends if none other are queued).

## System information

 * **Airsonic version**: 11.0.0-SNAPSHOT.20210630215318 – June 30, 2021 at 4:53:18 PM CDT
 * **Operating system**: Linux 4.9.241-arm64 #1 SMP PREEMPT aarch64 GNU/Linux (DietPi 7.3.2)
 * **Java version**: java 11.0.11
 * **Proxy server**: nginx/1.14.2
 * **Client**: Chrome 91.0.4472.147 or DSub 5.5.1 or Ultrasonic 2.21.0
 * **Language**: English

## Additional notes

Again all these FLAC files displayed and played properly prior to the upgrade/change tonight from Airsonic to Airsonic-Advanced. Nothing else has been modified.

**Comment by randomnicode** [comment] 2021-07-02 11:58
Want to upload a sample flac file that shows a 0 duration?

**Comment by donutmiddles** [comment] 2021-07-02 13:10
Sure thing, looks like it won't let me attach directly as a FLAC, so I've zipped one of them.
[01 - Life Less Ordinary.zip](https://github.com/airsonic-advanced/airsonic-advanced/files/6754752/01.-.Life.Less.Ordinary.zip)

**Comment by randomnicode** [comment] 2021-07-02 13:36
Hmmm, this file seems to work fine for us locally. Duration looks fine and plays okay

![image](https://user-images.githubusercontent.com/45723468/124281374-81d99200-dafe-11eb-8c39-1bb6e64553af.png)

The web browser requires transcoding before it plays flac files, so the issue is likely there. Can you check:
- The default transcoding string for flac->mp3 should be `ffmpeg -i %s -map 0:0 -b:a %bk -v 0 -f mp3 -`
- Your ffmpeg is recent (with flac support) and properly installed

**Comment by donutmiddles** [comment] 2021-07-02 13:50
Hm, interesting.

The transcoding string I have for flac > mp3 is ffmpeg -i %s -map 0:0 -b:a %bk -v 0 -f mp3 -
The ffmpeg version I have is ffmpeg version 4.1.6-1~deb10u1
The files that are showing good and the ones that are showing 0:00 are in the same places they've been for some quite some time, mapped to an nfs share mount. The db is writeable as I'm able to add new files and re-scan and they show up fine. Also file permissions are the same as with the older Airsonic and assigned to the proper user:group.

The only things I had done before the upgrade were to stop the airsonic service, wget the latest airsonic.war from the snapshot and restart the service.

To attach the db, would I zip the whole db directory?

**Comment by randomnicode** [comment] 2021-07-02 16:17
> To attach the db, would I zip the whole db directory?

yup!

**Comment by donutmiddles** [comment] 2021-07-02 17:35
Ok, will do! Thanks for the help as well, btw. In the meantime what I did was revert back to the backup I had of Airsonic 10.6.2 and try to play some of the files again. They did play fine this time, but I noticed something in the logs that seems like it may be relevant. Also I noticed in my DSub Android client that there wouldn't be a track duration listed until the cache had downloaded fully, even though it did play.

2021-07-02 10:59:04.097  WARN --- o.a.p.service.TranscodingService         : Unknown duration for 01 - Simple Lessons. Unable to estimate transcoded size.
2021-07-02 10:59:04.099  INFO --- o.a.p.io.PlayQueueInputStream            : 172.17.50.1:  listening to (1995) Lucy [FLAC]/01 - Simple Lessons.flac
2021-07-02 10:59:04.115  WARN --- o.a.p.service.TranscodingService         : Unknown duration for 01 - Simple Lessons. Unable to estimate transcoded size.
2021-07-02 10:59:04.116  INFO --- o.a.p.io.TranscodeInputStream            : Starting transcoder: [/mnt/dietpi_userdata/airsonic/transcode/ffmpeg] [-i] [/mnt/qnap/Subsonic/FLAC/With .cue (Complete)/C/Candlebox/(1995) Lucy [FLAC]/01 - Simple Lessons.flac] [-map] [0:0] [-b:a] [320k] [-v] [0] [-f] [mp3] [-]

I'll go ahead and reupgrade to the lastest EDGE release for Airsonic-Advanced and try again.

**Comment by donutmiddles** [comment] 2021-07-02 18:32
2021-07-02 13:30:13.674  INFO --- o.a.p.c.StreamController                 : 172.17.50.1: listening to (2004) Indian Summer [FLAC]/01 - Life Less Ordinary.flac
2021-07-02 13:30:13.686  INFO --- o.a.p.s.CacheConfiguration$CacheLogger   : Cache Key: /mnt/qnap/Subsonic/FLAC/With .cue (Complete)/C/Carbon Leaf/(2004) Indian Summer [FLAC] | EventType: REMOVED | Old value: (2004) Indian Summer [FLAC] | New value: null
2021-07-02 13:30:13.694  INFO --- o.a.p.io.TranscodeInputStream            : Starting transcoder: [/mnt/dietpi_userdata/airsonic/transcode/ffmpeg][-i][/mnt/qnap/Subsonic/FLAC/With .cue (Complete)/C/Carbon Leaf/(2004) Indian Summer [FLAC]/01 - Life Less Ordinary.flac][-map][0:0][-b:a][320k][-v][0][-f][mp3][-]
2021-07-02 13:30:14.128  WARN --- o.a.p.c.StreamController                 : Stream output exceeded expected length of 80000. It is likely that the transcoder is not adhering to the bitrate limit or the media source is corrupted or has grown larger

**Comment by donutmiddles** [comment] 2021-07-02 18:38
Attached the db zip file. :-)
[db.zip](https://github.com/airsonic-advanced/airsonic-advanced/files/6756448/db.zip)

**Comment by donutmiddles** [comment] 2021-07-04 21:03
Update - Got this fixed! What I ended up doing was essentially clearing the database and re-refreshing everything:

Settings > Media Folders
Unchecked "Enable" on all the folder.
Scanned the database.
Cleaned the database.
Rechecked "Enable" on all the folders.
Performed a full scan of the media folders.

Thanks again for the efforts!

**Comment by randomnicode** [comment] 2021-07-06 17:34
Can we close this issue if it was resolved?

**Closed** 2021-07-06 17:35 UTC

**Comment by gerroon** [comment] 2021-11-10 21:26
I have this issue as well during playback from Ultrasonic

 WARN --- o.a.p.c.StreamController                 : Stream output exceeded expected length of 64000. It is likely that the transcoder is not adhering to the bitrate limit or the media source is corrupted or has grown larger
